insert into main.exercise_how_to (exercise_id, name, url)
values (
    3,
    'youtube',
    'https://www.youtube.com/watch?v=2-o_-HTPhv8'
  ),
  (
    4,
    'youtube',
    'https://www.youtube.com/watch?v=o2qSVwxiFk4'
  ),
  (
    5,
    'youtube',
    'https://www.youtube.com/watch?v=9vYCwtHkWgI'
  ),
  (
    6,
    'youtube',
    'https://www.youtube.com/watch?v=WvLMauqrnK8'
  ),
  (
    7,
    'youtube',
    'https://www.youtube.com/watch?v=x-8iKS2Tcxk'
  ),
  (
    8,
    'youtube',
    'https://train.getswole.app/exercises/bent-over-dumbbell-rear-delt-raise-garage-2-0/'
  ),
  (
    9,
    'youtube',
    'https://www.youtube.com/watch?v=NwzUje3z0qY'
  ),
  (
    10,
    'youtube',
    'https://www.youtube.com/watch?v=ul0Z_skxUeI'
  ),
  (
    11,
    'youtube',
    'https://www.youtube.com/watch?v=VzIcGAgBiaM'
  ),
  (
    12,
    'youtube',
    'https://www.youtube.com/watch?v=6Fzep104f0s'
  ),
  (
    13,
    'youtube',
    'https://www.youtube.com/watch?v=Orxowest56U'
  ),
  (
    14,
    'youtube',
    'https://www.youtube.com/watch?v=m0FOpMEgero'
  ),
  (
    15,
    'youtube',
    'https://www.youtube.com/watch?v=MujQbvXr2vE'
  ),
  (
    16,
    'youtube',
    'https://www.youtube.com/watch?v=pAplQXk3dkU'
  ),
  (
    17,
    'youtube',
    'https://www.youtube.com/watch?v=5_ejbGfdAQE'
  ),
  (
    18,
    'youtube',
    'https://www.youtube.com/watch?v=YCKPD4BSD2E'
  ),
  (19, 'youtube', 'https://youtu.be/FDay9wFe5uE'),
  (
    20,
    'youtube',
    'https://www.youtube.com/watch?v=G_8LItOiZ0Q'
  ),
  (
    21,
    'youtube',
    'https://www.youtube.com/watch?v=brFHyOtTwH4'
  ),
  (
    22,
    'youtube',
    'https://www.youtube.com/watch?v=6GMKPQVERzw'
  ),
  (
    23,
    'youtube',
    'https://www.youtube.com/watch?v=cYKYGwcg0U8'
  ),
  (
    24,
    'youtube',
    'https://www.youtube.com/watch?v=ZS2poP_Wc04'
  ),
  (
    25,
    'youtube',
    'https://www.youtube.com/watch?v=NLDBFtSNhqg'
  ),
  (
    26,
    'youtube',
    'https://www.youtube.com/watch?v=q5X9thiKofE'
  ),
  (
    27,
    'youtube',
    'https://www.youtube.com/watch?v=flmMqsi3rl0'
  ),
  (
    28,
    'youtube',
    'https://www.youtube.com/watch?v=efDlxayx234'
  ),
  (
    29,
    'youtube',
    'https://www.youtube.com/watch?v=YQ2s_Y7g5Qk'
  ),
  (
    30,
    'youtube',
    'https://www.youtube.com/watch?v=q7H4AQPQAz0'
  ),
  (
    31,
    'youtube',
    'https://www.youtube.com/watch?v=7IV729pBFUc'
  ),
  (
    32,
    'youtube',
    'https://www.youtube.com/watch?v=GG6EjB3ZVf4'
  ),
  (33, 'youtube', 'https://youtu.be/UCXxvVItLoM'),
  (34, 'youtube', 'https://youtu.be/fvtbQuAG1sg'),
  (
    36,
    'youtube',
    'https://www.youtube.com/watch?v=EK747VC37yE'
  ),
  (
    37,
    'youtube',
    'https://www.youtube.com/watch?v=tZUYS7X50so'
  ),
  (
    38,
    'youtube',
    'https://www.youtube.com/watch?v=cEaIlD7BCW0'
  ),
  (
    39,
    'youtube',
    'https://www.youtube.com/watch?v=sExoXhSZzNQ'
  ),
  (
    40,
    'youtube',
    'https://www.youtube.com/watch?v=I34ysEkPK7w'
  ),
  (
    41,
    'youtube',
    'https://www.youtube.com/watch?v=YRg2hyPjp9E'
  ),
  (
    42,
    'youtube',
    'https://www.youtube.com/watch?v=isMOXCRkywQ'
  ),
  (
    44,
    'youtube',
    'https://www.youtube.com/watch?v=zgToz5FiI-E'
  ),
  (
    46,
    'youtube',
    'https://www.youtube.com/watch?v=oVq4fkh5pFs'
  ),
  (
    47,
    'youtube',
    'https://www.youtube.com/watch?v=HKbDU850mbE'
  ),
  (
    49,
    'youtube',
    'https://www.youtube.com/watch?v=8iPEnn-ltC8'
  ),
  (
    50,
    'youtube',
    'https://www.youtube.com/watch?v=_O1xunCfYEM'
  ),
  (
    51,
    'youtube',
    'https://www.youtube.com/watch?v=h8cVvPpleCA'
  ),
  (
    52,
    'youtube',
    'https://www.youtube.com/watch?v=bMBxJsBgTao'
  ),
  (
    53,
    'youtube',
    'https://www.youtube.com/watch?v=pfSMst14EFk'
  ),
  (
    54,
    'youtube',
    'https://www.youtube.com/watch?v=HHxNbhP16UE'
  ),
  (
    55,
    'youtube',
    'https://www.youtube.com/watch?v=U5pviWt7sMo'
  ),
  (
    56,
    'youtube',
    'https://www.youtube.com/watch?v=TTFDQnOLq6Y'
  ),
  (
    57,
    'youtube',
    'https://www.youtube.com/watch?v=m0FOpMEgero'
  ),
  (
    58,
    'youtube',
    'https://www.youtube.com/watch?v=SxW1G0ahSBc'
  ),
  (
    59,
    'youtube',
    'https://www.youtube.com/watch?v=SLOtxuaStoQ'
  ),
  (
    60,
    'youtube',
    'https://www.youtube.com/watch?v=P5sXHLmXmBM'
  ),
  (
    61,
    'youtube',
    'https://www.youtube.com/watch?v=FiQUzPtS90E'
  ),
  (
    62,
    'youtube',
    'https://www.youtube.com/watch?v=48ORDkT24tY'
  ),
  (
    64,
    'youtube',
    'https://www.youtube.com/watch?v=SQOsKWSHTMo'
  ),
  (
    65,
    'youtube',
    'https://www.youtube.com/watch?v=osHzkwG-9JE'
  ),
  (
    66,
    'youtube',
    'https://www.youtube.com/watch?v=RD_A-Z15ER4'
  ),
  (
    67,
    'youtube',
    'https://www.youtube.com/watch?v=U1OanW26I78'
  ),
  (
    68,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    69,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    70,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    71,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    72,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    73,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    74,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    77,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    82,
    'youtube',
    'https://www.youtube.com/watch?v=h2sXIR3S-hU'
  ),
  (
    84,
    'youtube',
    'https://youtu.be/kmbzQJoRMUU?t=125'
  ),
  (85, 'youtube', 'https://youtu.be/gRIX9uEYVZk'),
  (
    86,
    'youtube',
    'https://www.youtube.com/watch?v=JnLFSFurrqQ'
  );