insert into main.training_type (name)
values ('bodybuilding'),
  ('strength'),
  ('yoga'),
  ('athletics'),
  ('karate'),
  ('stretch'),
  ('stability'),
  ('cardiovascular'),
  ('agility'),
  ('endurance'),
  ('rehabilitation'),
  ('mobility'),
  ('power'),
  ('speed'),
  ('flexibility'),
  ('calisthenics'),
  ('coordination'),
  ('functional');